### ISSUE TITLE
add topic molecular-dynamics

### ISSUE THREAD

**Issue by Beliavsky** [FPhilippi/prealpha#1]
I suggest adding the topic `molecular-dynamics` in the About section.

**Comment by FPhilippi** [comment]
you mean in the readme? it's already mentioned in there...

**Comment by Beliavsky** [comment]
No, it should like the About section at https://github.com/lammps/lammps . How to add a topic is described at https://docs.github.com/en/enterprise-server@3.0/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by FPhilippi** [comment]
That should be done now - thank you very much!
